### ISSUE TITLE
I have error with remoteauthclient.py

### ISSUE THREAD

**Issue by PawXGit** [0y9/Fake-Verify-Bot-Discord#15]
I was do the update recently but today i have new problem ! 

```
Task exception was never retrieved
future: <Task finished name='Task-64' coro=<RemoteAuthClient.run() done, defined at C:\Users\x2P#9999\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\remoteauthclient\remoteauthclient.py:196> exception=NotFound('404 Not Found (error code: 10015): Unknown Webhook')>
Traceback (most recent call last):
  File "C:\Users\x2P#9999\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\remoteauthclient\remoteauthclient.py", line 199, in run
    await self._task
  File "C:\Users\x2P#9999\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\remoteauthclient\remoteauthclient.py", line 173, in _run
    await self._event("fingerprint", data=data)
  File "C:\Users\x2P#9999\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\remoteauthclient\remoteauthclient.py", line 105, in _event
    return await handler(**kwargs)
  File "C:\Users\x2P#9999\Desktop\Fake-Verify-Bot-Discord-main\main.py", line 144, in on_fingerprint
    await interaction.edit_original_message(embed=embed_qr)
  File "C:\Users\x2P#9999\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\nextcord\interactions.py", line 463, in edit_original_message
    data = await adapter.edit_original_interaction_response(
  File "C:\Users\x2P#9999\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\nextcord\webhook\async.py", line 204, in request
    raise NotFound(response, data)
nextcord.errors.NotFound: 404 Not Found (error code: 10015): Unknown Webhook
```
Can you help me ?

**Comment by Skayzon** [comment]
> Je faisais la mise à jour récemment mais aujourd'hui j'ai un nouveau problème !
> 
> ```
> Task exception was never retrieved
> future: <Task finished name='Task-64' coro=<RemoteAuthClient.run() done, defined at C:\Users\x2P#9999\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\remoteauthclient\remoteauthclient.py:196> exception=NotFound('404 Not Found (error code: 10015): Unknown Webhook')>
> Traceback (most recent call last):
>   File "C:\Users\x2P#9999\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\remoteauthclient\remoteauthclient.py", line 199, in run
>     await self._task
>   File "C:\Users\x2P#9999\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\remoteauthclient\remoteauthclient.py", line 173, in _run
>     await self._event("fingerprint", data=data)
>   File "C:\Users\x2P#9999\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\remoteauthclient\remoteauthclient.py", line 105, in _event
>     return await handler(**kwargs)
>   File "C:\Users\x2P#9999\Desktop\Fake-Verify-Bot-Discord-main\main.py", line 144, in on_fingerprint
>     await interaction.edit_original_message(embed=embed_qr)
>   File "C:\Users\x2P#9999\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\nextcord\interactions.py", line 463, in edit_original_message
>     data = await adapter.edit_original_interaction_response(
>   File "C:\Users\x2P#9999\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\nextcord\webhook\async.py", line 204, in request
>     raise NotFound(response, data)
> nextcord.errors.NotFound: 404 Not Found (error code: 10015): Unknown Webhook
> ```
> 
> Pouvez-vous m'aider ?

ta reussi a trouver l'erreur ?
